# Generated by Django 4.2.3 on 2024-11-12 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0003_category_developertype_resume_workexperience_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='about_me',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='name',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='percentage',
        ),
        migrations.RemoveField(
            model_name='workexperience',
            name='role',
        ),
        migrations.AddField(
            model_name='resume',
            name='about',
            field=models.TextField(default=2, help_text="O'zingiz haqingizda qisqacha ma'lumot"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='name',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='asosiy.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='proficiency',
            field=models.IntegerField(default=0, help_text='Malaka darajasi (0-100)'),
        ),
        migrations.AddField(
            model_name='skill',
            name='skill_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workexperience',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workexperience',
            name='position',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='resume',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='asosiy.category'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='developer_type',
            field=models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('fullstack', 'Fullstack')], max_length=255),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='company_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.DeleteModel(
            name='DeveloperType',
        ),
    ]
