# Generated by Django 4.2.3 on 2024-11-12 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0004_remove_resume_about_me_remove_skill_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Malaka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daraja', models.IntegerField()),
                ('nomi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiy.category')),
            ],
        ),
        migrations.CreateModel(
            name='Tajriba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kompaniya', models.CharField(max_length=200)),
                ('yil', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Turi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='resume',
            name='about',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='category',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='developer_type',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='name',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='work_experience',
        ),
        migrations.AddField(
            model_name='resume',
            name='ozi_haqida',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.DeleteModel(
            name='WorkExperience',
        ),
        migrations.AddField(
            model_name='tajriba',
            name='kim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiy.turi'),
        ),
        migrations.AddField(
            model_name='resume',
            name='kim',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='asosiy.turi'),
            preserve_default=False,
        ),
    ]
