# Generated by Django 4.2.3 on 2024-11-12 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0005_malaka_tajriba_turi_remove_resume_about_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tajriba',
            name='yil',
            field=models.CharField(max_length=200),
        ),
    ]
