# Generated by Django 4.2.3 on 2024-11-13 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0008_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='link2',
            field=models.URLField(null=True),
        ),
    ]
