# Generated by Django 4.2.3 on 2024-11-13 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0011_contactmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='sent_at',
        ),
    ]
